const navigationStrings = {
  LOGIN: "Login",
  SIGNUP: "SignUp",
  HELP_SIGNING_IN: "HelpSigningIn",
  OTP_VERIFICATION: "OtpVerification",
  PROFILE: "Profile",
  FORGOT_PASSWORD: "ForgotPassword",
  RESET_PASSWORD: "ResetPassword",
  SET_USER_PIN: "SetUserPin",
  VERIFY_IDENTITY: "VerifyIdentity",
  ACCEPT_CONSENT: "AcceptConsent",
  SET_PREFERENCES: "SetPreferences",
  SYNC: "Sync",
  HOME: "Home",
  APPOINTMENTS: "Appointments",
  SCHEDULE_STEP_1: "ScheduleStep1",
  SCHEDULE_STEP_2: "ScheduleStep2",
  NOTIFICATIONS: "Notifications",
  LABS: "Labs",
  LAB_REQUEST: "LabRequest",
  LAB_RESULTS: "LabResults",
  LAB_RESULT_DETAIL: "LabResultDetail",
};

export default navigationStrings;
