const navigationStrings = {
  LOGIN: "Login",
  SIGNUP: "SignUp",
  HELP_SIGNING_IN: "HelpSigningIn",
  OTP_VERIFICATION: "OtpVerification",
  /** Pick Face ID / PIN / OTP after OTP verify / when routing cold-start onboarding */
  CHOOSE_LOGIN_METHOD: "ChooseLoginMethod",
  PROFILE: "Profile",
  FORGOT_PASSWORD: "ForgotPassword",
  RESET_PASSWORD: "ResetPassword",
  USER_PIN: "UserPin",
  VERIFY_IDENTITY: "VerifyIdentity",
  ACCEPT_CONSENT: "AcceptConsent",
  SET_PREFERENCES: "SetPreferences",
  SYNC: "Sync",
  /** Root tab host (Home · Message · Med Refills · More) */
  BOTTOM_NAVIGATION: "BottomNavigation",
  HOME: "Home",
  APPOINTMENTS: "Appointments",
  APPOINTMENT_DETAIL: "AppointmentDetail",
  APPOINTMENT_CONFIRM: "AppointmentConfirm",
  APPOINTMENT_SCHEDULED: "AppointmentScheduled",
  WELLNESS_MEDSPA: "WellnessMedSpa",
  TREATMENT_MENU: "TreatmentMenu",
  BOOK_APPOINTMENT: "BookAppointment",
  BOOK_APPOINTED: "BookAppointed",
  BEFORE_AFTER_GALLERY: "BeforeAfterGallery",
  TREATMENT_RESULT: "TreatmentResult",
  MEMBERSHIP: "Membership",
  COMPLETE_SUBSCRIPTION: "CompleteSubscription",
  SUBSCRIPTION_COMPLETED: "SubscriptionCompleted",
  SCHEDULE_STEP_1: "ScheduleStep1",
  SCHEDULE_STEP_2: "ScheduleStep2",
  NOTIFICATIONS: "Notifications",
  LABS: "Labs",
  IMAGING: "Imaging",
  IMAGING_REQUEST: "ImagingRequest",
  IMAGING_RESULTS: "ImagingResults",
  IMAGING_RESULTS_DETAILS: "ImagingResultsDetails",
  VIEW_REPORT: "ViewReport",
  VIEW_PDF: "ViewPdf",
  BILLING: "Billing",
  STATEMENT_DETAIL: "StatementDetail",
  PAYMENT_SUCCESSFUL: "PaymentSuccessful",
  MY_RECORDS: "MyRecords",
  IMMUNIZATION_RECORD: "ImmunizationRecord",
  FORMS_LIBRARY: "FormsLibrary",
  PRACTICE_DOCUMENTS: "PracticeDocuments",
  LAB_REQUEST: "LabRequest",
  LAB_RESULTS: "LabResults",
  LAB_RESULT_DETAIL: "LabResultDetail",
  /** More tab — profile, support, and app settings */
  SETTINGS: "Settings",
  MY_PROFILE: "MyProfile",
  EDIT_PROFILE: "EditProfile",
  COMMUNICATION: "Communication",
  PRIVACY_SECURITY: "PrivacySecurity",
  DEVICE_SESSIONS: "DeviceSessions",
  HELP_TRAINING: "HelpTraining",
  SUPPORT_TICKET: "SupportTicket",
  TICKET_SUBMISSION: "TicketSubmission",
  EMERGENCY_SAFETY: "EmergencySafety",
  MED_REFILLS: "MedRefills",
};

export default navigationStrings;
