import type { StaffFilter, StaffMember } from "./staffTypes";

export const FILTER_WIDTHS: Record<StaffFilter, number> = {
  all: 52,
  ma: 118,
  billing: 78,
  front: 104,
  office: 148,
};

export const STAFF_LIST: StaffMember[] = [
  {
    id: "1",
    name: "Sarah Williams",
    phone: "(555) 987-6543",
    dob: "21 Mar 1980",
    email: "sarah@example.com",
    roleLabel: "MA / Nurse",
    role: "ma",
  },
  {
    id: "2",
    name: "James Porter",
    phone: "(555) 234-8899",
    dob: "12 Aug 1976",
    email: "james@example.com",
    roleLabel: "Billing",
    role: "billing",
  },
  {
    id: "3",
    name: "Elena Ruiz",
    phone: "(555) 441-2201",
    dob: "03 Feb 1991",
    email: "elena@example.com",
    roleLabel: "Front Desk",
    role: "front",
  },
  {
    id: "4",
    name: "Maria Lopez",
    phone: "(555) 120-7788",
    dob: "19 Nov 1988",
    email: "maria@example.com",
    roleLabel: "MA / Nurse",
    role: "ma",
  },
  {
    id: "5",
    name: "David Chen",
    phone: "(555) 330-4410",
    dob: "07 Jan 1982",
    email: "david@example.com",
    roleLabel: "Office Manager",
    role: "office",
  },
  {
    id: "6",
    name: "John Doe",
    phone: "(555) 123-4567",
    dob: "01 Jan 1990",
    email: "john@example.com",
    roleLabel: "MA / Nurse",
    role: "ma",
  },
  {
    id: "7",
    name: "Jane Doe",
    phone: "(555) 789-0123",
    dob: "01 Jan 1990",
    email: "jane@example.com",
    roleLabel: "Billing",
    role: "billing",
  },
];
