const navigationStrings = {
  //AUTH
  LOGIN: "Login",
  SIGNUP: "SignUp",
  OTP_VERIFICATION: "OtpVerification",
  FORGOT_PASSWORD: "ForgotPassword",
  RESET_PASSWORD: "ResetPassword",
  //APP
  HOME: "Home",
  PRACTICE_INTELLIGENCE: "PracticeIntelligence",
  PRACTICE_SCHEDULE: "PracticeSchedule",
  MY_CALENDER: "MyCalender",
  TO_DO_LIST: "ToDoList",
  CREATE_TASK: "CreateTask",
  ADD_EVENT: "AddEvent",
  EVENT_DETAILS: "EventDetails",
  REPORT_HUB: "ReportHub",
  SCHEDULE: "Schedule",
  QUEUE: "Queue",
  PATIENTS: "Patients",
  PATIENT_SNAPSHOT: "PatientSnapshot",
  REFILL_ESCALATION: "RefillEscalation",
  REFILL_REQUEST_DETAILS: "RefillRequestDetails",
  DELEGATE_REVIEW_TO_STAFF: "DelegateReviewToStaff",
  LABS_REVIEW: "LabsReview",
  ORDER_LABS: "OrderLabs",
  REFILL_SCHEDULE_VISIT: "RefillScheduleVisit",
  PRESCRIPTION_REFILLS: "PrescriptionRefills",
  REFILL_SENT: "RefillSent",
  REQUEST_REVIEW_SENT: "RequestReviewSent",
  PATIENT_MESSAGE_PREVIEW: "PatientMessagePreview",
  LABS_DASHBOARD: "LabsDashboard",
  LAB_ALERT_DECISION: "LabAlertDecision",
  LABS_DETAIL: "LabsDetail",
  LAB_LOCATION: "LabLocation",
  ORDER_SENT: "OrderSent",
  MESSAGE_PATIENT: "MessagePatient",
  SCHEDULE_VISIT: "ScheduleVisit",
  FULL_PATIENT_CHART: "FullPatientChart",
  VITALS: "Vitals",
  MED_SPA: "MedSpa",
  HOSPITAL_ROUNDS: "HospitalRounds",
  FOLLOW_UPS: "FollowUps",
  PRE_OPS: "PreOps",
  PHYSICALS: "Physicals",
};

export default navigationStrings;
